code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension Shan.code-settings-sync
code --install-extension Tyriar.sort-lines
code --install-extension WallabyJs.quokka-vscode
code --install-extension alefragnani.project-manager
code --install-extension bierner.color-info
code --install-extension christian-kohler.path-intellisense
code --install-extension chrmarti.regex
code --install-extension dbaeumer.vscode-eslint
code --install-extension doublefint.pgsql
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension lukehoban.Go
code --install-extension mjmcloug.vscode-elixir
code --install-extension octref.vetur
code --install-extension robertohuertasm.vscode-icons
code --install-extension tomoki1207.vscode-input-sequence
code --install-extension wmaurer.change-case
code --install-extension yzhang.markdown-all-in-one